### ISSUE TITLE
Seg Fault on exit

### ISSUE THREAD

**Issue by clive-g-brown** [bitstormGER/ArrayFire-Nim#2]
I am trying to use this library, however it seg faults on program exit, all the prior code is fine. It looks like a memory management or GC issue. Any ideas?

ArrayFire v3.6.4 (OpenCL, 64-bit Mac OSX, build 1b8030c5)
[0] APPLE: AMD Radeon Pro Vega 64 Compute Engine, 16368 MB
past
Traceback (most recent call last)
SIGSEGV: Illegal storage access. (Attempt to read from nil?)00

**Comment by bitstormFA** [comment]
Hi,

First of all many thanks for the report! 

Could you try to provide some code which triggers this? 
I have only a NVidia card here and the last time I tested I did not get this error. 
I remember some problems switching backends but I need to validate.

I did not look into this for quite some time but I am planning to update this to current nim and arrayfire versions but please allow for some time to get this implemented.

**Comment by clive-g-brown** [comment]
Hi thanks for replying -

all of the test suite code does it *on exit* - although the ArrayFire code itself works fine. Feels like a GC or double free ? I stepped into the library and its balking at an OpenCL free call, like something is getting free somewhere else. This is on AMD and Intel chips, OSX, latest ArrayFire binary libs.

But for example - if I run the below with just the matrix call - on exit - it will seg fault, the other lines don't cause any issue when run alone - :

I tried destroy(a) and af_free(addr(a)) - no change.

#
#  arrayfire tests
#

import strutils
import ArrayFire
import system

var s = get_available_backends()
info()    

var a = matrix(3,3, 1..9,s32)

**Comment by clive-g-brown** [comment]
"I did not look into this for quite some time but I am planning to update this to current nim and arrayfire versions but please allow for some time to get this implemented."

Very supportive of you bringing this up to date - I would like to port some algorithms to it. If you need any help with that, let me know.

**Comment by clive-g-brown** [comment]
so, it only does this in global scope, it is one of Nim or ArrayFire trying to clean up allocs before the other one, the seg fault is in af_<cleanup>_array or some such.

**Comment by bitstormFA** [comment]
I have finally updated to arrayfire 3.7.2 and nim 1.2.6.
With the updates I can't reproduce the error you reported. 
I have added code to basic_test.nim which tests for this problem. 
I am still looking on how to test on mac os but on the only platform I can test on at the moment (arch linux) I do consider the problem to be solved

**Comment by bitstormFA** [comment]
I couldn't reproduce with arrayfire 3.8.0 - if you see the error again please open a new issue
